### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by amaalzohny**

### CODE REVIEW

**Review by IaroslavR — COMMENTED** [review]
Maybe you made this PR by error? In this repo no dirs like in your regex

**Comment by amaalzohny** [comment]
> Maybe you made this PR by error? In this repo, no dirs like in your regex

@IaroslavR  maybe you correct me here, what I wanted to do is to ignore the libs|scripts|modules folders and its content from this step,   is this the right way to do?

**Comment by limcheehow** [comment]
@IaroslavR 

according to @amaalzohny , for viewer lambda, it did not exclude libs|scripts|modules. Is this not the right way to solve it?

**Comment by amaalzohny** [comment]
@IaroslavR  @limcheehow  :
at viewer its already done here  https://github.com/tapway/terraform-aws-lambda-viewer/blob/de7b9fe88e57bdce7eac9e29d9dd934f02ea737d/.pre-commit-config.yaml#L19

but somehow it's not running  with me to exclude the libs folder , 
that's why i added this PR to the main ansible, 
if it's not useful here, plz close the PR , or correct me

**Review by raju-tapway — CHANGES_REQUESTED** [review]
@amaalzohny you can test your code by placing your changes to [here](https://github.com/tapway/terraform-aws-lambda-viewer/blob/81b45435f444934a457991c416f69e1a8319e89e/.pre-commit-config.yaml#L1). It should not be in this repo as @IaroslavR mentioned.

**Comment by limcheehow** [comment]
@amaalzohny precommit config should be run for each repo only. Don't think this plays any role whatsoever. If you talk about Github Actions to run precommit, you should update it here - https://github.com/tapway/terraform-aws-lambda-viewer/blob/de7b9fe88e57bdce7eac9e29d9dd934f02ea737d/.github/workflows/pre-commit.yml

Please go ahead and do it.

**Pull request closed without merging**
